title: "Your website title"
url: "https://monsoonmalabar.com/ykruqilcsphwzyrkhdc"
email: "kmeyers508@yahoo.com"
markdown: kramdown
mobile: ''
country: ''
location: ''
sass:
  sass_dir: _sass
  style: compressed
collections:
  products:
    output: true
defaults:
  - scope:
      type: posts
    values:
      layout: product
  - scope:
      type: products
    values:
      layout: post
plugins_dir:
  - jekyll-sitemap
  - jekyll-paginate
encoding: UTF-8
include: ['.well-known']
permalink: /products/:title/
paginate: 4
paginate_path: 'page/:num/'
favicon: 'https://monsoonmalabar.com/ykruqilcsphwzyrkhdc/logo.png'
paypal: ''
analytics: ''
adsense: ''